services:
  nfs-server:
    build:
      context: ./nfs-server
    image: nfs-server
    container_name: nfs-server
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    volumes:
      - type: bind
        source: ./nfs-server/exports
        target: /etc/exports
      - type: volume
        source: nfs-volumes
        target: /exports
    restart: always
    # # For Export External Network
    # ports: 
    #   - "2049:2049"
    #   - "20048:20048"
  nfs-client:
    build:
      context: ./nfs-client
      args:
        - USER=${USER:-user} # # Your User Name
        - USER_ID=${USER_ID:-1000} # Your User ID
        - GROUP_ID=${GROUP_ID:-1000} # Your GROUP ID
    image: nfs-client
    container_name: nfs-client
    cap_add:
      - SYS_ADMIN
    volumes:
      - type: bind
        source: ./nfs-client/fstab
        target: /etc/fstab
    tty: true
    restart: always
    command: bash

volumes:
  nfs-volumes:
    name: nfs-volumes