apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volumes
  namespace: nfs
  labels:
    app: nfs-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
